# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14b2v9L_rn8r0V2L6U9OLpPJr5RtItkYc
"""

pip install youtube-transcript-api

from urllib.parse import urlparse, parse_qs
from youtube_transcript_api import YouTubeTranscriptApi

def extract_video_id(url: str) -> str:
   """
    Extract the YouTube video ID from a URL.
    Raises ValueError if no 'v' parameter is found.
   """
   parsed = urlparse(url)
   qs = parse_qs(parsed.query)
   video_ids = qs.get('v')

   if not video_ids:
      raise ValueError(f"No video id found in URL: {url}")
   return video_ids[0]

if __name__ == "__main__":
  url = "https://www.youtube.com/watch?v=IKsNzvPUr8g&pp=ygUVcGljdG9ibG94IGV4cGxhbmF0aW9u"

  video_id = extract_video_id(url)

  api = YouTubeTranscriptApi()
  fetched = api.fetch(video_id, languages=['en']) # returns a FetchedTranscript

  text = "\n".join(snippet.text for snippet in fetched)
  print(text)

from huggingface_hub import login
login()

from transformers import pipeline

summarizer = pipeline("summarization", model="Falconsai/text_summarization")

ARTICLE = text
summary= summarizer(ARTICLE, max_length=1000, min_length=30, do_sample=False)

print(summary[0]["summary_text"])